[variables]
NODE_VERSION = "23"
NIXPACKS_NODE_VERSION = "23"

[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm start"
