[variables]
NODE_VERSION = "24"
NIXPACKS_NODE_VERSION = "24"

[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm start"
